{% extends 'template/php/pimcore/Dockerfile.sh.twig' %}

{% block phpExtensions %}
RUN apt-get update \
 && apt-get install -y \
    autoconf \
    automake \
    libtool \
    pkg-config \
    libz-dev \
    build-essential \
    g++ \
 && docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp \
 && docker-php-ext-install intl mbstring mysqli bcmath gd bz2 soap xsl pdo pdo_mysql fileinfo exif ftp zip opcache ldap sockets \
 && pecl install redis apcu xdebug imagick/imagick@master pcov amqp excimer \
 && docker-php-ext-enable redis imagick apcu xdebug pcov amqp excimer ftp \
 && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
 && docker-php-ext-install imap \
 && docker-php-ext-enable imap \
 && apt-get autoremove -y \
 && apt-get remove -y autoconf automake libtool pkg-config libz-dev build-essential g++ \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
{% endblock %}