default:
    tags:
        - 'bsc-aws-x86'
    interruptible: true
    image: registry.gitlab.com/basecom-public/docker/image/docker

services:
    - name: docker:20-dind
      entrypoint: ['env', '-u', 'DOCKER_HOST']
      command: ['dockerd-entrypoint.sh', '--experimental']

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_CLI_EXPERIMENTAL: enabled
    PROJECT_DIR: .

stages:
    - build
    - publish
    - clean

before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

.build image:
    stage: build
    script:
        - docker buildx create --platform "${PLATFORM}" --use
        - |
            docker buildx build \
                --push \
                --platform ${PLATFORM} \
                --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}-cache-${ARCH} \
                --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}-cache-${ARCH} \
                -f ${PROJECT_DIR}/build/${IMAGE_NAME}/${PHP_VERSION}/${IMAGE_VARIANT}/${SYSTEM}/Dockerfile \
                -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}-${ARCH} \
                ${PROJECT_DIR}

.publish image:
    stage: publish
    script:
        - |
            docker manifest create ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG} \
                --amend ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}-amd \
                --amend ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}-arm
        - docker manifest push ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}

.clean image tags:
    stage: clean
    variables:
        REG_SHA256: ade837fc5224acd8c34732bf54a94f579b47851cc6a7fd5899a98386b782e228
        REG_VERSION: 0.16.1
    before_script:
        - apk add --no-cache curl
        - curl --fail --show-error --location "https://github.com/genuinetools/reg/releases/download/v$REG_VERSION/reg-linux-amd64" --output /usr/local/bin/reg
        - echo "$REG_SHA256  /usr/local/bin/reg" | sha256sum -c -
        - chmod a+x /usr/local/bin/reg
    script:
        - /usr/local/bin/reg rm -d --auth-url ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${IMAGE_TAG}-arm
        - /usr/local/bin/reg rm -d --auth-url ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${IMAGE_TAG}-amd

include:
    - local: /gitlab-ci/includes.yaml
