# syntax=docker/dockerfile:1
FROM php:{{ php.version }}-{{ php.variant }}-{{ general.distribution }}

LABEL org.opencontainers.image.authors="DevOps Team <devops@basecom.de>"
LABEL org.opencontainers.image.vendor="basecom GmbH & Co. KG"

# install composer from composer image
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

# set timezone
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# install system extensions
{% block systemExtensions %}
{% endblock %}

# install php extensions
{% block phpExtensions %}
{% endblock %}

# install additional packages
{% block additionalPackages %}
{% endblock %}

{% if php.variant == 'cli' %}
# install supercronic
COPY php/install_supercronic.sh /opt/

RUN bash /opt/install_supercronic.sh
{% endif %}

# configure xDebug
RUN echo "xdebug.idekey = PHPSTORM" >> /usr/local/etc/php/conf.d/20-xdebug.ini; \
    echo "xdebug.mode = off" >> /usr/local/etc/php/conf.d/20-xdebug.ini; \
    echo "xdebug.start_with_request = yes" >> /usr/local/etc/php/conf.d/20-xdebug.ini; \
    echo "xdebug.discover_client_host = 1" >> /usr/local/etc/php/conf.d/20-xdebug.ini; \
    echo "xdebug.client_host = 127.0.0.1" >> /usr/local/etc/php/conf.d/20-xdebug.ini;

# Configure bash
RUN mkdir -p /opt/bsc/bash \
 && touch /opt/bsc/bash/.bash_history

ENV HISTFILE=/opt/bsc/bash/.bash_history

# Configure user and permissions
RUN addgroup --gid 1000 application \
 && adduser --uid 1000 --gid 1000 application

RUN chown -R 1000:1000 /opt/bsc \
 && chown -R 1000:1000 /var/www
