build docker stable:
    stage: build
    extends: .docker buildx
    tags:
        - 'docker'
    script:
        - |
            docker buildx build \
            --push \
            --platform linux/arm64/v8,linux/amd64 \
            --cache-from ${CI_REGISTRY_IMAGE}/docker:cache \
            --cache-to ${CI_REGISTRY_IMAGE}/docker:cache \
            -t ${CI_REGISTRY_IMAGE}/docker:stable \
            ${CI_PROJECT_DIR}

