# pimcore php 8.1 fpm
build pimcore php-8.1-fpm amd:
    extends: .build image kaniko
    variables:
        IMAGE_NAME: php
        IMAGE_TAG: 8.1-fpm-pimcore
        PHP_VERSION: '8.1'
        IMAGE_VARIANT: fpm
        SYSTEM: pimcore
        PLATFORM: linux/amd64
        ARCH: amd

build pimcore php-8.1-fpm arm:
    extends: .build image kaniko
    tags:
         - 'bsc-eks-arm64'
    variables:
        IMAGE_NAME: php
        IMAGE_TAG: 8.1-fpm-pimcore
        PHP_VERSION: '8.1'
        IMAGE_VARIANT: fpm
        SYSTEM: pimcore
        PLATFORM: linux/arm64/v8
        ARCH: arm

publish pimcore php-8.1-fpm:
    extends: .publish image
    variables:
        IMAGE_NAME: php
        IMAGE_TAG: 8.1-fpm-pimcore
    needs:
        - build pimcore php-8.1-fpm amd
        - build pimcore php-8.1-fpm arm

#build pimcore php-8.1-fpm:
#    extends: .build image buildx
#    variables:
#        IMAGE_NAME: php
#        IMAGE_TAG: 8.1-fpm-pimcore
#        PHP_VERSION: '8.1'
#        IMAGE_VARIANT: fpm
#        SYSTEM: pimcore
