build pimcore php-8.3-fpm amd:
    extends: .build image
    variables:
        IMAGE_NAME: php
        IMAGE_TAG: 8.3-fpm-pimcore
        PLATFORM: linux/amd64
        ARCH: amd

build pimcore php-8.3-fpm arm:
    extends: .build image
    variables:
        IMAGE_NAME: php
        IMAGE_TAG: 8.3-fpm-pimcore
        PLATFORM: linux/arm64/v8
        ARCH: arm

publish pimcore php-8.3-fpm:
    extends: .publish image
    variables:
        IMAGE_NAME: php
        IMAGE_TAG: 8.3-fpm-pimcore
    needs:
        - build pimcore php-8.3-fpm amd
        - build pimcore php-8.3-fpm arm
