name: 'Cleanup Docker registry'

on:
    workflow_call:
        inputs:
            image_registry:
                type: string
                description: 'Image registry'
                required: true
            dry_run:
                type: boolean
                description: 'Dry run'
                required: false
                default: true

env:
    REGISTRY: ghcr.io

jobs:
    cleanup:
        name: Cleanup regisitry
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            - name: Download digests
              uses: actions/download-artifact@v4
              with:
                  path: /tmp/build-metadata
                  pattern: build-metadata-*
                  merge-multiple: true

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Fetch multi-platform package version SHAs
              id: multi-arch-digests
              working-directory: /tmp/build-metadata/image-tags
              run: |
                  imageNames=""
                  for identifier in *; do
                      imageNameAndTag="$(cat ${identifier})"
                      imageName=$(echo $imageNameAndTag | cut -d: -f1)
                      
                      imageNames="$imageNames $imageName"
                  done

                  unqiueImageNames=$(echo $imageNames | tr ' ' '\n' | sort -u | tr '\n' ' ')
                  echo "image-names=$unqiueImageNames" >> $GITHUB_OUTPUT

            - uses: snok/container-retention-policy@v3.0.0
              with:
                  account: basecom
                  token: ${{ secrets.GITHUB_TOKEN }}
                  image-names: ${{ steps.multi-arch-digests.outputs.image-names }}
                  cut-off: 2h
                  dry-run: ${{ github.event.inputs.dry_run }}
